// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClyzcF35l0etpRptMYGr-ElorlhD-lHY8',
    appId: '1:735059350833:web:54b4b64780c9736ac30c10',
    messagingSenderId: '735059350833',
    projectId: 'hf-v3-1',
    authDomain: 'hf-v3-1.firebaseapp.com',
    storageBucket: 'hf-v3-1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqN6GbXR5-tXgwlajJAuODP6U3rerGtcE',
    appId: '1:735059350833:android:4e410fcc2b017e19c30c10',
    messagingSenderId: '735059350833',
    projectId: 'hf-v3-1',
    storageBucket: 'hf-v3-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVOdr__wt8YqDCCK9LcaKT9OJkQQmdguA',
    appId: '1:735059350833:ios:f3fbfe4f2d50b66bc30c10',
    messagingSenderId: '735059350833',
    projectId: 'hf-v3-1',
    storageBucket: 'hf-v3-1.firebasestorage.app',
    iosBundleId: 'com.example.hfV3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVOdr__wt8YqDCCK9LcaKT9OJkQQmdguA',
    appId: '1:735059350833:ios:f3fbfe4f2d50b66bc30c10',
    messagingSenderId: '735059350833',
    projectId: 'hf-v3-1',
    storageBucket: 'hf-v3-1.firebasestorage.app',
    iosBundleId: 'com.example.hfV3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClyzcF35l0etpRptMYGr-ElorlhD-lHY8',
    appId: '1:735059350833:web:6f5600b575888e3dc30c10',
    messagingSenderId: '735059350833',
    projectId: 'hf-v3-1',
    authDomain: 'hf-v3-1.firebaseapp.com',
    storageBucket: 'hf-v3-1.firebasestorage.app',
  );
}
