import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'package:flutter_localizations/flutter_localizations.dart'; // For localization
import 'l10n/app_localizations.dart'; // Generated by Flutter Intl

// Import the custom AppTheme
import 'package:hf_v3/common/theme/app_theme.dart'; // Updated path to hf_v3

// Import the AuthWrapper to handle initial routing based on auth state
import 'package:hf_v3/common/widgets/auth_wrapper.dart'; // Updated path to hf_v3

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(
    const ProviderScope(
      // Wrap the app with ProviderScope for Riverpod
      child: MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Healthy Families',
      // Use the centralized theme defined in AppTheme
      theme: AppTheme.lightTheme,
      // Configure localization delegates
      localizationsDelegates: const [
        AppLocalizations.delegate, // Custom app localizations
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: const [
        Locale('en'), // English
        Locale('es'), // Spanish
      ],
      home: const AuthWrapper(), // Start with AuthWrapper to manage auth flow
    );
  }
}
